# Generated by Django 3.0.6 on 2020-12-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PaymentCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=None, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=False)),
                ("coins", models.IntegerField()),
                ("user_claim", models.CharField(blank=True, max_length=100, null=True)),
                ("account_id", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "PaymentCode",
                "verbose_name_plural": "PaymentCodes",
            },
        ),
        migrations.CreateModel(
            name="PaymentLogs",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=None, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("reference_id", models.CharField(max_length=100)),
                ("account_id", models.IntegerField()),
                ("username", models.CharField(max_length=30)),
                ("coins", models.IntegerField()),
                ("status", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "PaymentLog",
                "verbose_name_plural": "PaymentLogs",
            },
        ),
    ]
