version: '3'

services:

  backend:
    build:
      context: .
      dockerfile: ./compose/development/django/Dockerfile
    image: mt2web-py
    env_file: 
      - ./.environment/development/.django
    environment:
      - DEBUG=1
    volumes:
      - ./src/:/app
    ports:
      - 8000:8000
