version: '3'

volumes:
  local_static_data: {}

services:

  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: luisito666/m2-api-rest:develop-6
    env_file: 
      - ./.environment/production/.django
    environment:
      - DEBUG=0
    volumes:
      - local_static_data:/home/data/www

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: nginx-mt2web-py-prod
    volumes:
      - local_static_data:/usr/share/nginx/html/static
    ports:
      - 80:80
