version: '3'

services:
  django:
    build:
      context: .
      dockerfile: ./compose/development/django/Dockerfile
    image: mt2web-py
    volumes:
      - ./src:/app
    env_file:
       - ./.environments/prod/django/.django
    ports:
      - 8000:8000
