version: '3'

services:

  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: mt2web-py-prod
    environment:
      - DEBUG=0
    volumes:
      - ./src:/app
    ports:
      - 8000:8000
