#! /usr/bin/env sh

set -o errexit
set -o pipefail
set -o nounset

python manage.py migrate
python manage.py collectstatic --no-input
gunicorn --bind 0.0.0.0:8000 -w 1 --threads 4 core.wsgi:application

exec "$@"
