#!/bin/sh

set -o errexit
set -o nounset

mysql_ready() {
python << END
import os
import sys
import pymysql

"""
    Get Env's and export
"""

try:
    pymysql.connect(
        host=os.environ['DATABASE_HOST'],
        port=int(os.environ['DATABASE_PORT']),
        user=os.environ['DATABASE_USER'],
        password=os.environ['DATABASE_PASSWORD'],
        database='account')
except pymysql.err.OperationalError:
    sys.exit(-1)
sys.exit(0)
END
}
until mysql_ready; do
  >&2 echo 'Esperando que el servidor MySQL este disponible...'
  sleep 1
done
>&2 echo 'MySQL esta disponible'

exec "$@"
