database:
  user: root
  password: 'database-password'
  host: 0.0.0.0
  port: 3306
server:
  name: 'Metin2 XxX'
  url: 'https://www.example.com'
  domain: 'example.com'
  timezone: 'America/Bogota'
  secret: 'some-secret-please-change'
paymentwall:
  public_key: ''
  private_key: ''
captcha:
  enable: False
  public_key: ''
  private_key: ''
mail:
  host: 0.0.0.0
  port: 25
  password: 'your-password'
  user: 'your-user@example.com'
register:
  send_activation_email: False
