database:
  user: root
  password: 'your_pasword'
  host: 0.0.0.0
  port: 3306
server:
  name: 'Metin2 XxX'
  url: 'https://www.example.com'
  domain: 'example.com'
  timezone: 'America/Bogota'
paymentwall:
  public_key: ''
  private_key: ''
captcha:
  enable: False
  public_key: ''
  private_key: ''
mail:
  host: 0.0.0.0
  port: 25
  password: 'your_pasword'
  user: 'your_user@example.com'
register:
  mail_activate_account: False
